[package]
name = "wss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main/main.rs"
name = "wss"

[dependencies]
aul = "1.2.0"
whdp = "1.1.5"

[features]
no-color = ["aul/no-color"]